export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SKILLS_LOAD = 'SKILLS_LOAD';
export const FEATURED = 'FEATURED';
export const DELETE_SKILL = 'DELETE_SKILL';
export const EDIT_SKILL = 'EDIT_SKILL';
export const CREATE_SKILL = 'CREATE_SKILL';
export const ADD_QUESTION = 'ADD_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const REORDER_QUESTION = 'REORDER_QUESTION';

export const ROLES_LOAD = 'ROLES_LOAD';
export const POPULAR = 'POPULAR';
export const DELETE_ROLE = 'DELETE_ROLE';
export const EDIT_ROLE = 'EDIT_ROLE';
export const CREATE_ROLE = 'CREATE_ROLE';
export const ATTACH_SKILL = 'ADD_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';

export const GUIDE_LOAD = 'GUIDE_LOAD';
export const GUIDE_SELECT_ROLE = 'GUIDE_SELECT_ROLE';
export const GUIDE_SELECT_DURATION = 'GUIDE_SELECT_DURATON';
export const GUIDE_ATTACH_SKILL = 'GUIDE_ATTACH_SKILL';
export const GUIDE_REMOVE_SKILL = 'GUIDE_REMOVE_SKILL';
export const GUIDE_ADD_QUESTION = 'GUIDE_ADD_QUESTION';
export const GUIDE_DELETE_QUESTION = 'GUIDE_DEL_QUESTION';
export const GUIDE_REORDER_QUESTION = 'GUIDE_REORDER_QUESTION';
export const GUIDE_ROLE_AUTOSUGGEST = 'GUIDE_ROLE_AUTOSUGGEST';
export const GUIDE_SKILL_AUTOSUGGEST = 'GUIDE_SKILL_AUTOSUGGEST';
export const GUIDE_TO_RUBRIC = 'GUIDE_TO_RUBRIC';
export const GUIDE_REQUEST_AUTH = 'GUIDE_REQUEST_AUTH';
export const GUIDE_CREATE = 'GUIDE_CREATE';
export const GUIDE_TO_FINISH = 'GUIDE_TO_FINISH';
export const GUIDE_LIST_LOAD = 'GUIDE_LIST_LOAD';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const UPDATE = 'UPDATE';
export const REFRESH = 'REFRESH';
